### ISSUE TITLE
anonymous ftp support

### ISSUE THREAD

**Issue by clach04** [timo-reymann/chrooted-ftp#29]
### Description

Any interest in anonymous ftp support? I'm trying to determine if it's worth a PR or if I should keep in a separate fork.

Thanks for making this project available! It made setup on my server much easier (and repeatable) :+1:

**Comment by timo-reymann** [comment]
Heya @clach04,
firstly, thanks for contributing! :)

I think anonymous ftp support could be very valuable, feel free to create a PR and I will merge it to the main project

Cheers
Timo

**Comment by clach04** [comment]
Hilariously I've not got this working yet, I'm being slightly thwarted by the permissions in-place on my drive :-D

    > ftp localhost
    Connected to localhost.
    220 Welcome to my dockerized FTP!
    Name (localhost:pi): ftp
    500 OOPS: vsftpd: refusing to run with writable root inside chroot()
    Login failed.
    421 Service not available, remote server has closed connection

it maybe a while before I get back to this (read-only anonymous ftp users), I got the main thing I need up and running (upload support for regular users).

**Comment by timo-reymann** [comment]
The following works:

```ini
anonymous_enable=YES
no_anon_password=YES
anon_root=/data/bob
```

Assuming there is a user, bob created.

So as long as the root for anonymous user is inside /data it seems to work, read-only.

I assume your use case is making one user's home available for anonymous users? - Than this would be the way to go.

My proposal would be to add an env var e.g., `ALIAS_ANONYMOUS_USER`, if set the anonymous access is enabled + the alias user is the root for anonymous. That should be a generic solution for your usecase.

**Comment by clach04** [comment]
That's essentially the config I have that fails with the writable warning :-(. I tried the idea to use the /data dir but same error,

**Comment by timo-reymann** [comment]
Closing this for now as there does not seem to be demand for it. 

If you get a working version of this and want to do a PR feel free 😊
