### ISSUE TITLE
support user home directory specification in user file

### ISSUE THREAD

**Issue by clach04** [timo-reymann/chrooted-ftp#30]
### Description

For example, current ftp user file is:

    username:password

Add support for optional home directory:

    username:password
    username_with_home_dir:password:/some/path

Similar question as #29. Any interest?

Other idea would be to add config option for the `/data` appended on the end of the  home path

**Comment by timo-reymann** [comment]
Heya @clach04,

thanks for the suggestion! :) 

Can you maybe elaborate a bit on why that is a feature you need? I am not quite sure what this could be used for, so quite curious about it.

Besides that, I think there were some problems that the user part needs to be in the same place for the chroot to work as the pattern is with `%u` as the placeholder for username:

https://github.com/timo-reymann/chrooted-ftp/blob/b2fe01a585234e57e7dffa3973575e48734fe2bd/scripts/entrypoint.sh#L113

**Comment by clach04** [comment]
I'm not sure if my use case is generic enough to make this a feature, I'm currently running with the following hack:

https://github.com/clach04/chrooted-ftp/commit/9319727ccbfb14d0a7a30159857fd1193303334e

It isn't pretty but it does work for me :-) My initial reason for this is a network scanner that scans (PDFs) directly to an ftp server. I am/was using OMV (but I'm having some hardware issues so migrating hardware with an existing disk layout). I did not want to maintain OS users on the host, so your containerized solution works well for me (but not the disk layout)

I have an NTFS/fat32 USB drive running from an SBC (similar to a raspberry pi), not directly relevant but the main point is that it's a filesystem with out "real" ACLs for read/write. I already have a bunch of files/directories on there that I want to share (or offer write access to).

I understand if this is not a useful feature, I'm happy to maintain my hacks :-)

**Comment by timo-reymann** [comment]
Ok, in that case, I would say it makes sense to have the layout configurable (via env var etc.).

So basically by default: `${DATA_FOLDER}/$username/data`, and configurable to e.g., `${DATA_FOLDER}/$username`.

You are welcome to create a PR for logic like this, and I am happy to add it. Even though I don't have any other requests or use cases like this, I would merge into mainline. Because I think it would reduce maintenance for you, as you don't need to maintain a separate fork.

**Comment by clach04** [comment]
> Ok, in that case, I would say it makes sense to have the layout configurable (via env var etc.).
> 
> So basically by default: `${DATA_FOLDER}/$username/data`, and configurable to e.g., `${DATA_FOLDER}/$username`.
> 
> You are welcome to create a PR for logic like this, and I am happy to add it. Even though I don't have any other requests or use cases like this, I would merge into mainline. Because I think it would reduce maintenance for you, as you don't need to maintain a separate fork.

Created https://github.com/timo-reymann/chrooted-ftp/issues/32 for this.

**Comment by clach04** [comment]
PR https://github.com/timo-reymann/chrooted-ftp/pull/33 opened for config over `/data` sub-directory.

Updated description with more detail on per-user home directory specification. Academically I think this idea has some merit, m personal use case is handled by #32, so I'm not likely to work on this.

**Comment by timo-reymann** [comment]
Merged #33, closing this :)

Thanks again for your contributions!
